
services:
  python-app:
    platform: linux/amd64
    image: bhavyadocker11/python-app-version-2.0:2.0
    build:
      context: .
    ports:
      - "8000:5000"
    volumes:
      - python_data:/var/lib/pythondata

volumes:
  python_data: {}

#networks:
